[dependencies]
quarto = ">=1.6.42,<2"

[tasks]

[tasks.doc]
cmd = "quarto render docs"

[tasks.doclive]
cmd = "quarto preview docs --port 7000"

[workspace]
authors = ["Lena PÃ¶pping <80910285+Zeyna777@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "k-matrix-day"
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]
version = "0.1.0"
